pom.groupId=org.jraf.klibperipage
pom.version=1.0.0-SNAPSHOT
pom.description=Kotlin library to access the Peripage thermal printer via BLE.
pom.vcsUrl=https://github.com/BoD/klibperipage
pom.developer=Benoit \'BoD\' Lubek
pom.license=Apache-2.0
java.compatibility=11
kotlin.compatibility=2.2.0
kdoc.allProjects=true
