{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jraf.klibperipage",
    "module": "klibperipage",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibperipage-metadata-1.0.0-SNAPSHOT.jar",
          "url": "klibperipage-1.0.0-SNAPSHOT.jar",
          "size": 5851,
          "sha512": "5453bcb77b5cc8fe9783d30c7347d7fe933af1507308a23eefa65b6bf5a324abb80ef4487bfaee8012691001309413b0a32855fad647db5571ec334fb8d6e775",
          "sha256": "a6804a7b016112f54201291afd038e44585a65ae73fda3d0b56be7b856452153",
          "sha1": "9fe0ab885ec1ad07cb01135cab2fa9cb19feedee",
          "md5": "cae5b2c7f5357d248d11df4b0ab68a94"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "klibperipage-kotlin-1.0.0-SNAPSHOT-sources.jar",
          "url": "klibperipage-1.0.0-SNAPSHOT-sources.jar",
          "size": 6920,
          "sha512": "f7d0f43346f9187af8ed0606d4ca47b53877651beb3be1b144cfc70bcd52eebcd9709c08a73df01c39ddabfb31bbcb405199d4d2ff76e9442353f02464b881ca",
          "sha256": "d4e9bb77e71fd3d88386a37621ec88a85d639936cfa1174e464578f58a65e922",
          "sha1": "5e9bd9fe0ab2d8ff06ed6c74922f9218fe7c7bcd",
          "md5": "8dfd22d0f96a3c575a93221b4fd1ab14"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibperipage-jvm/1.0.0-SNAPSHOT/klibperipage-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibperipage",
        "module": "klibperipage-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibperipage-jvm/1.0.0-SNAPSHOT/klibperipage-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibperipage",
        "module": "klibperipage-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../klibperipage-jvm/1.0.0-SNAPSHOT/klibperipage-jvm-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibperipage",
        "module": "klibperipage-jvm",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibperipage-macosarm64/1.0.0-SNAPSHOT/klibperipage-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibperipage",
        "module": "klibperipage-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibperipage-macosarm64/1.0.0-SNAPSHOT/klibperipage-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibperipage",
        "module": "klibperipage-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../klibperipage-macosarm64/1.0.0-SNAPSHOT/klibperipage-macosarm64-1.0.0-SNAPSHOT.module",
        "group": "org.jraf.klibperipage",
        "module": "klibperipage-macosarm64",
        "version": "1.0.0-SNAPSHOT"
      }
    }
  ]
}
